<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.playwright</groupId>
  <artifactId>PlaywrightJavaPractice</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <properties>
	<playwright.version>1.51.0</playwright.version>
  </properties>
  
  <dependencies>
	
	<!-- https://mvnrepository.com/artifact/com.microsoft.playwright/playwright -->
	<dependency>
	    <groupId>com.microsoft.playwright</groupId>
	    <artifactId>playwright</artifactId>
	    <version>${playwright.version}</version>
	</dependency>
	
  </dependencies>
  
</project>